name: firebase_auth_oauth_web
description: Web implementation for `firebase_auth_oauth`.  Don't use directly. Instead import `firebase_auth_oauth` plugin.
version: 0.2.1
author: Amr Yousef <contact@amryousef.me>
homepage: https://github.com/amrfarid140/firebase_auth_oauth/tree/master/firebase_auth_oauth_web

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
#  firebase_auth_oauth_platform_interface: ^0.2.1
  firebase: ^8.0.0
  js: ^0.6.2
  firebase_auth: ^0.20.0+1
  firebase_core: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_auth_oauth_platform_interface:
    git:
      url: https://github.com/kostasoft/firebase_auth_oauth
      path: firebase_auth_oauth_platform_interface
  pedantic: ^1.9.2

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FirebaseAuthOAuthWeb
        fileName: firebase_auth_oauth_web.dart
